### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'string')

### ISSUE THREAD

**Issue by junkblocker** [jmerle/zeal-user-contrib#13]
```
/home/foobar/node/node_modules/cli-ux/lib/styled/table.js:285
        columns: command_1.flags.string({ exclusive: ['extended'], description: 'only show provided columns (comma-separated)' }),
                                 ^

TypeError: Cannot read properties of undefined (reading 'string')
    at /home/foobar/node/node_modules/cli-ux/lib/styled/table.js:285:34
    at Object.<anonymous> (/home/foobar/node/node_modules/cli-ux/lib/styled/table.js:314:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/foobar/node/node_modules/cli-ux/lib/index.js:14:36)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)                                                                                                                        /0.3s
1: zeal-user-contrib
```

**Comment by jmerle** [comment]
Sorry for the late reply. I am unable to reproduce this error, can you please share your Node.js version (`node -v`)?

**Comment by junkblocker** [comment]
```
% node -v
v16.11.1
```

**Comment by jmerle** [comment]
I still have no idea what may be causing your error. It's a weird one because zeal-user-contrib does not have a (transitive) dependency on cli-ux, which the error is coming from. I did however just update all of zeal-user-contrib's dependencies, so maybe that fixes it? You can update by re-running the command you used to install zeal-user-contrib.

**Comment by junkblocker** [comment]
That seems to have fixed it. Thanks!
